<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'failed'                           => 'These credentials do not match our records.',
    'password'                         => 'The provided password is incorrect.',
    'throttle'                         => 'Too many login attempts. Please try again in :seconds seconds.',
    'iati_publishing_tool'             => 'IATI Publishing Tool',
    'iati_publishing_tool_description' => 'Welcome to IATI Publisher. Use this tool to start your IATI
                                           publishing journey. Enter your login information if you\'re already
                                           a user or create a new account if you\'re new here.',
    'registered_yet'                   => 'Haven\'t registered yet?',
    'join_now'                         => 'Join Now',
    'member_sign_in'                   => 'Already a member? Sign In',
    'sign_in'                          => 'Sign In',
    'Welcome_back'                     => 'Welcome back! Please enter your details.',
    'username'                         => 'Username',
    'password_label'                   => 'Password',
    'confirm_password'                 => 'Confirm Password',
    'full_name'                        => 'Full Name',
    'email_address'                    => 'Email Address',

    'forget_password'                  => 'Forget your password?',
    'reset'                            => 'Reset',
    'join_now_description'             => 'To being this journey, tell us your preference and we\'ll guide you
                                           through this process.',
    'unregistered_account'             => 'I am new to IATI',
    'unregistered_account_description' => 'Use this option if your organization has not registered an account
                                           with IATI on the IATI Registry',
    'registered_account'               => 'My organisation has registered with IATI',
    'registered_account_description'   => 'Use this option if your organization is listed as an IATI publisher
                                           of the IATI Registry',
    'not_sure'                         => 'Not sure which one to select?',
    'contact_support'                  => 'Contact Support',
    'create_account'                   => 'Create IATI Publisher Account',
    'create_account_description'       => 'Register your organisation to start your IATI publishing journey by
                                           creating an account in IATI publisher.',
    'publisher_information'            => 'Publisher Information',
    'iati_registry_information'        => 'Sorry, the information you provided doesn’t match your IATI
                                          Registry information.',
    'registry_information'             => 'Please note that if you’re an account holder in IATI Registry,
                                            make sure your
                                            <span class="font-bold"
                                              >Publisher Name,Publisher ID and IATI Organisation ID</span
                                            >
                                            match your IATI Registry Information. Contact
                                            <span
                                              ><a
                                                class="text-n-40 hover:text-n-50"
                                                href="mailto:support@iatistandard.org"
                                                >support@iatistandard.org</a
                                              ></span
                                            >
                                            for more details.',
    'publisher_name'                   => 'Publisher Name',
    'publisher_name_error'             => 'Publisher Name doesn’t match your IATI Registry information.',
    'publisher_id'                     => 'Publisher ID',
    'publisher_id_description'         => 'You can use a unique abbreviated form of your organization name',
    'publisher_id_error'               => 'Publisher ID doesn’t match with your IATI Registry information',
    'country'                          => 'Country',
    'registration_agency'              => 'Organisation Registration Agency',
    'registration_number'              => 'Organisation Registration Number',
    'iati_organiational_identifier'    => 'IATI Organisational Identifier',
    'help_text'                        => 'This is autogenerated, please make sure to fill the above
                                           fields correctly.',
    'already_have_account'             => 'Already have an account?',
    'next_step_button'                 => 'Next Step',
    'go_back_button'                   => 'Go Back',
    'steps'                            => 'Step 1 out of 3',
    'publisher_description'            => 'This information will be used to create a Publisher in
                                            IATI Publisher.',
    'administrator'                    => 'Administrator Information',
    'administrator_description'        => 'This information will be used to create an admin account in IATI Publisher',
    'email_verification'               => 'Email Verification',
    'email_description'                => 'Please verify and activate your IATI Publisher account through your provided email.',
    'administrator_information'        => 'Administrator Information',
    'verify_account'                   => 'Please verify your account',
    'verification_email'               => 'A verification email has been sent to',
    'verification_email'               => 'A verification email has been sent to',
    'verify_and_active'                => 'Please click on the link in the email to verify and activate your
                                           new IATI publisher account.',
    'get_started_button'               => 'Get Started',
    'password_recovery'                => 'Password Recovery',
    'enter_your_email'                 => 'Please enter your email, we will send you a link to reset your
                                           password',
    'email'                            => 'Email',
    'send_password'                    => 'Send password reset link',
    'password_recovery_description'    => 'An email has been sent with further instructions, please check
                                           it out when you get it.',
    'reset_password'                   => 'Reset Password',
    'reset_password_description'       => 'Please enter your new password',
    'new_password'                     => 'New Password',
    'repeat_password'                  => 'Repeat Password',

    'hover_text' => [
      'publisher_name_description'     => 'The Name of the organisation publishing the data.',
      'publisher_id_description'       => 'This will be the unique identifier for the publisher.
                                           Where possible use a short abbreviation of your organisation\'s
                                           name. For example: \'dfid\' or \'worldbank\' Must be at least
                                           two characters long and lower case. Can include letters, numbers
                                           and also - (dash) and _ (underscore).',
      'country_description'            => 'Choose from the dropdown the country in which the publisher
                                           is legally incorporated.',
      'iati_organiational_description' => 'The organisation identifier used in the IATI XML files to
                                           identify the reporting organisation.',
      'username_description'           => 'This was auto-generated using organisation abbreviaton you
                                           provided earlier.',
    ]
];
