<?php

return [
    'activity_identifier' => [
        'label'       => "activity-identifier",
        'hover_text'  => "",
        'placeholder' => "Type activity identifier here",
        'help'        => "Enter a unique series of letters and / or numbers to identify your activity. For example PROJECT-00120467 or AFG-COVAX.</br></br>You must make sure:</br></br>Each IATI identifier you publish is unique.</br></br>Each IATI identifier should not start or end with whitespace.</br></br>Only use numbers, letters and dashes to form your IATI identifiers.</br></br>Once you have published an activity its IATI identifier must not change.<a target='_blank' href='https://iatistandard.org/en/guidance/standard-overview/preparing-your-data/activity-information/creating-iati-identifiers/'>Further guidance.</a>",
        'narrative'   => [],
    ],
    'iati_identifier'     => [
        'label'       => "iati-identifier",
        'hover_text'  => "A globally unique identifier for the activity.</br></br>This MUST be prefixed with EITHER the current IATI organisation identifier for the reporting organisation (reporting-org/@ref) OR a previous identifier reported in other-identifier, and suffixed with the organisation’s own activity identifier. The prefix and the suffix should be separated by a hyphen “-“.</br></br>Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates.<a target='_blank' href='https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/iati-identifier/'>For more information</a>",
        'placeholder' => "",
        'help'        => "This is autogenerated by adding your activity-identifier to the end of your Organisation Identifier (this is the unique ID that was generated for your organisation when you registered). <a target='_blank' href='https://iatistandard.org/en/guidance/standard-overview/preparing-your-data/activity-information/creating-iati-identifiers/'>Futher guidance</a>.</br></br>Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates. <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/iati-identifier/'>For more information.</a>",
        'narrative'   => [],
    ],
    'reporting_org'       => [
        'label'       => "reporting-org",
        'hover_text'  => "This is your IATI Organisation Identifier (it is the unique ID that was generated for your organisation when you registered).<a target='_blank' href='https://iatistandard.org/en/guidance/publishing-data/registering-and-managing-your-organisation-account/how-to-create-your-iati-organisation-identifier/'>For more information.</a>",
        'placeholder' => "",
        'help'        => "The organisation issuing the report. May be a primary source (reporting on its own activity as donor, implementing agency, etc) or a secondary source (reporting on the activities of another organisation).</br></br>Specifying the @ref attribute is mandatory. May contain the organisation name as content.    <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/reporting-org/'>For more information</a>",
        'narrative'   => [
            'label'       => "narrative",
            'hover_text'  => "The name of the organisation. This can be repeated in multiple languages. <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/transaction/provider-org/'>For more information</a>",
            'placeholder' => "",
            'help'        => "This is the name you provided for your organisation when you registered.",
        ],
        'language'    => [
            'label'       => "language",
            'hover_text'  => "A code specifying the language of text in this element. It is recommended that wherever possible only codes from ISO 639-1 are used. If not present, the default language is assumed. <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/description/narrative/'>For more information</a>",
            'placeholder' => "Select language",
            'help'        => "Select the language of the text you provided in the narrative. If no language is selected, your default language is assumed.",
            'narrative'   => []
        ],
    ],
    'title'               => [
        'label'       => "title",
        'hover_text'  => "A short, human-readable title that contains a meaningful summary of the activity. May be repeated for different languages. <a target=\"_blank\" href=\"https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/\">For more information</a>",
        'placeholder' => "ADD ADDITIONAL TITLE",
        'help'        => "",
        'narrative'   => [
            'label'       => "narrative",
            'hover_text'  => "The free text name or description of the item being described. This can be repeated in multiple languages. <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/document-link/title/narrative/'>For more information</a>",
            'placeholder' => "",
            'help'        => "Provide the title for this activity. For example: \"Water for Women Malawi\"."
        ],
        'language'    => [
            'label'       => "language",
            'hover_text'  => "A code specifying the language of text in this element. It is recommended that wherever possible only codes from ISO 639-1 are used. If not present, the default language is assumed. <a target='_blank' href='https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/document-link/title/narrative/'>For more information</a>",
            'placeholder' => "Select language",
            'help'        => "Select the language of the text you provided in the narrative. If no language is selected, your default language is assumed."

        ]
    ],

//
//        'reporting_org' => [
//            'label'      => 'reporting-org',
//            'hover_text' => 'The organisation issuing the report. Maybe a primary source (reporting on its own activity as donor, implementing agency, etc) or a secondary source (reporting on the activities of another organisation).<br><br>Specifying the @ref attribute is mandatory. May contain the organisation name as content. <a target="_blank" href="https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/reporting-org/">For more information</a>',
//        ],
//
//        'iati_identifier' => [
//            'label'      => 'iati-identifier',
//            'definition' => ''
//        ],
//
//        'other_identifier' => [
//            'label'      => 'other-identifier',
//            'definition' => ''
//        ],
//
//        'description' => [
//            'label'          => 'description',
//            'definition'     => 'A longer, human - readable description containing a meaningful description of the activity . May be repeated for different languages . <a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/description/" >for more information </a > ',
//            'add_additional' => 'ADD ADDITIONAL DESCRIPTION',
//            'help'           => ' Select the type of description that best describes your activity .<br ><br > 1. <b > General </b > -Unstructured, long description of the activity .<br ><br > 2. <b > Objectives</b > -Specific objectives for the activity, e . g . taken from logical framework .<br ><br > 3. <b > Target Groups </b > -Details of groups that are intended to benefit from the activity .<br ><br > 4. <b > Other</b > - for miscellaneous use. A further classification or breakdown may be included in the narrative '
//        ],
//
//        'type' => [
//            'label'      => 'type',
//            'definition' => 'Activity description types . (General, objectives, etc).<a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/codelists/descriptiontype/" >for more information </a > '
//        ],
//
//        'activity_status_label'  => 'activity - status',
//        'activity_date'          => [
//            'label'          => 'activity - date',
//            'definition'     => 'The planned and actual start and completion dates of the activity . Start dates may reflect either the commencement of funding, planning or physical activity . End dates should, wherever possible, reflect the ending of physical activity .<a target = "_blank" href = "https://iatistandard.org/en/guidance/standard-guidance/activity-dates-status/" >for more information </a > ',
//            'add_additional' => 'ADD ADDITIONAL ACTIVITY DATE',
//            'help'           => 'Please select the type of activity date that you will report .<br ><br > 1. <b > Planned start </b >: The date on which the activity is planned to start, for example the date of the first planned disbursement or when physical activity starts .<br ><br > 2. <b > Actual start </b >: The actual date the activity starts, for example the date of the first disbursement or when physical activity starts .<br ><br > 3. <b > Planned End </b >: The date on which the activity is planned to end, for example the date of the last planned disbursement or when physical activity is complete .<br ><br > 4. <b > Actual end </b >: The actual date the activity ends, for example the date of the last disbursement or when physical activity is complete . '
//        ],
//        'iso_date'               => [
//            'label'      => 'iso date',
//            'definition' => 'This attribute is required .<br > This value must be of type xsd:date .<br > 1: The planned start date of the activity must be before the planned end date .<br > 2: The actual start date of the activity must be before the actual end date .<br > 3: The actual start date of the activity must not be in the future .<br > 4: The actual end date of the activity must not be in the future .<a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/activity-date/" >for more information </a > ',
//            'help'       => 'Provide the date of your activity'
//        ],
//        'activity_scope_label'   => 'activity - scope',
//        'recipient_county_label' => 'recipient - country',
//        'recipient_region_label' => 'recipient - region',
//        'sector'                 => [
//            'label'      => 'sector',
//            'definition' => 'A recognised code, from a recognised vocabulary, classifying the purpose of the activity . Sector MUST EITHER be reported here or at transaction level for ALL transactions . <a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/sector/" >for more information </a > ',
//            'help'       => ' Provide information on the sector which the activity targets or supports . for example, primary education or agriculture . You can select more than one sector but you must provide < b>at least one </b >.',
//        ],
//
//        'vocabulary' => [
//            'label'      => 'vocabulary',
//            'definition' => 'An IATI code for the vocabulary (see codelist) used for sector classifications. If omitted, OECD DAC 5-digit Purpose Codes are assumed. It is recommended that OECD DAC 5-digit Purpose Codes are used wherever possible. It is also recommended that if a publisher has its own classification system or systems then the vocabularies 99 or 98 (Reporting Organisation’s own vocabularies) should be used in addition to DAC codes.<a target="_blank" href="https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/sector/">For more information</a>',
//            'help'       => ' Please choose the sector list from which you will select the sectors that your activity targets. IATI recommends choosing the OECD DAC 5-digit sector codelist, in which you can make a selection from over 300 sectors.<br><br>In addition to the OECD DAC 5-digit codelist, you can also choose to use another list (see <a target="_blank" href="https://iatistandard.org/en/iati-standard/203/codelists/sectorvocabulary/">information on all possible options</a>). If you want to use your organisation’s own list of internal sector classifications, select the option: ‘Reporting Organisation’.<br><br>You can choose to use multiple lists. If you use more than one internal sector classification, select ‘Reporting Organisation 2’ (which has the code 98) for the additional list.<a target="_blank" href="https://iatistandard.org/en/guidance/standard-guidance/activity-thematic-focus/">Further guidance.</a>'
//        ],
//
//        'code' => [
//            'label'      => 'code',
//            'definition' => 'The code for the sector. This attribute is required.<a target="_blank" href="https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/sector/">For more information</a>',
//            'help'       => 'Select the sector which the activity is targeting or supporting. You can choose more than one sector.'
//        ],
//
//        'percentage' => [
//            'label'      => 'percentage',
//            'definition' => 'The percentage of total commitments or total activity budget to this item. Content must be a decimal number between 0 and 100 inclusive, with no percentage sign. All reported sectors from the same vocabulary MUST add up to 100. <a target="_blank" href="https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/sector/">For more information</a>',
//            'help'       => 'If you have selected more than one sector (from the same list), each sector must be given a percentage. These percentages can then be applied to the funding amounts to estimate the resources allocated to each sector. For example, using the OECD DAC 5-digit sector codelist you could allocate 50% of the funding for the activity to the sector code ‘teacher training’ (11130) and 50% to ‘primary education’ (11220). '
//        ],
//
//        'narrative'=>[
//            'label'=>'narrative',
//            'definition'=>'',
//            'help'=>''
//        ]
//
//        'tag_label'                  => 'tag',
//        'policy_maker_label'         => 'policy - maker',
//        'collaboration_type_label'   => 'collaboration - type',
//        'default_flow_type_label'    => 'default-flow - type',
//        'default_finance_type_label' => 'default-finance - type',
//        'default_aid_type_label'     => 'default-aid - type',
//        'default_tied_status_label'  => 'default-tied - status',
//        'country_budget_items_label' => 'country - budget - items',
//        'humanitarian_scope_label'   => 'humanitarian - scope',
//        'capital_spend_label'        => 'capital - spend',
//        'related_activity_label'     => 'related - activity',
//        'conditions_label'           => 'conditions',
//        'legacy_data_label'          => 'legacy - data',
//        'document_link_label'        => 'document - link',
//        'contact_info_label'         => 'contact - info',
//        'location_label'             => 'location',
//        'planned_disbursement_label' => 'planned - disbursement',
//        'participating_org_label'    => 'participating - org',
//        'budget_label'               => 'budget',
//        'budget_definition'          => 'The value of the activity’s budget for each financial quarter or year over the lifetime of the activity . The purpose of this element is to provide predictability for recipient planning on an annual basis . The status explains whether the budget being reported is indicative or has been formally committed . <a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/budget/" >for more information </a > ',
//        'result_label'               => 'result',
//        'transactions_label'         => 'transactions',
//        'transactions_definition'    => 'Transactions recording committed or actual funds flowing in or out of an aid activity .<a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/transaction/" >for more information </a > ',
//        'narrative_label'            => 'narrative',
//        'narrative_definition'       => 'The free text name or description of the item being described . This can be repeated in multiple languages . <a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/narrative/" >for more information </a > ',
//        'language'                   => [
//            'label'       => 'language',
//            'placeholder' => 'Select language',
//            'definition'  => 'A code specifying the language of text in this element . It is recommended that wherever possible only codes from ISO 639 - 1 are used . if not present, the default language is assumed . <a target = "_blank" href = "https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/narrative/" >for more information </a > ',
//        ],
//        'help_hint'                  => 'help',
//        'hint'                       => 'Select the language of the text you provided in the narrative . if no language is selected, your default language is assumed . ',
];
