<?php
return array (
  'create_iati_publisher_header' => 'Create IATI Publisher Account and IATI Registry Account',
  'create_iati_publisher_subheader' => 'Register your organisation to start your IATI publishing journey by creating accounts in IATI publisher and IATI Registry at once.',
  'information_doesnt_match_registry' => 'Sorry, the information you provided doesn’t match your IATI Registry information.',
  'if_you_are_account_holder' => 'Please note that if you’re an account holder in',
  'make_sure_your' => 'make sure your',
  'match_your_iati_registry_info' => 'match your IATI Registry Information',
  'publisher_information' => 
  array (
    'label' => 'Publisher Information',
    'description' => 'This information will be used to create a Publisher in IATI Publisher',
    'hover_text' => 'We refer to organisations who publish IATI data as \'Publishers\'. Before publishing data, all organisations need their own \'Publisher Account\' on the IATI Registry (iatiregistry.org). Enter your organisation\'s data here and we\'ll create your organisation\'s Publisher Account for you. These details will also be saved here in IATI Publisher.',
  ),
  'publisher_name' => 
  array (
    'label' => 'Publisher Name',
    'placeholder' => 'Type your organisation name here',
    'hover_text' => 'The name of your organisation publishing the data.',
  ),
  'publisher_id' => 
  array (
    'label' => 'Publisher ID',
    'placeholder' => 'Type your organisation ID here',
    'hover_text' => 'Provide a unique ID for your organisation. It must be at least two characters long and use lower case letters. You can include letters, numbers and also - (dash) and _ (underscore). Where possible use a short abbreviation of your organisation\'s name, for example: \'nef_mali\' for Near East Foundation Mali.',
  ),
  'country' => 
  array (
    'label' => 'Country',
    'placeholder' => 'Select a Country',
    'hover_text' => 'Add the location of your organisation.',
  ),
  'org_registration_agency' => 
  array (
    'label' => 'Organisation Registration Agency',
    'placeholder' => 'Select an Organisation Registration Agency',
    'hover_text' => 'Select the agency in your country where your organisation is registered. If you do not know this information please email <a href=\'mailto:support@iatistandard.org\' target=\'_blank\'>support@iatistandard.org</a>',
  ),
  'org_registration_no' => 
  array (
    'label' => 'Organisation Registration Number',
    'placeholder' => 'Type your Registration Number here',
    'hover_text' => 'Add the registration number for your organisation that has been provided by the registration agency named above.',
  ),
  'registration_number' => 
  array (
    'label' => 'Registration Number',
    'placeholder' => 'Type your Registration Number here',
    'hover_text' => 'Provide the registration number for your organisation that has been provided by organisation registration agency. If you do not know this please email <a href=\'mailto:support@iatistandard.org\' target=\'_blank\'>support@iatistandard.org</a>.',
  ),
  'iati_org_identifier' => 
  array (
    'label' => 'IATI Organisational Identifier',
    'hover_text' => 'The Organisation Identifier is a unique code for your organisation. This is genereated from the Organisation Registration Agency and Registration Number. For more information read:  <a href="http://iatistandard.org/en/guidance/preparing-organisation/organisation-account/how-to-create-your-iati-organisation-identifier/" target="_blank">How to create your IATI organisation identifier.</a>',
    'help_text' => 'This is autogenerated, please make sure to fill the above fields correctly.',
  ),
  'publisher_type' => 
  array (
    'label' => 'Publisher Type',
    'placeholder' => 'Select a publisher type',
    'hover_text' => 'Select the type that best describes your organisation.  <a href="https://iatistandard.org/en/iati-standard/203/codelists/organisationtype/" target="_blank"> Read more on Organisation types.</a>',
  ),
  'publisher_logo_url' => 
  array (
    'label' => 'Publisher Logo Url',
    'hover_text' => ' Provide a link to an image to your organisation\'s logo (Optimum size: 200 x 120 px)',
  ),
  'organisation_desc' => 
  array (
    'label' => 'Organization Description',
    'placeholder' => 'Type Description here',
    'hover_text' => ' Provide a short description about your organisation.',
  ),
  'contact_info' => 
  array (
    'title' => 'Contact Information',
  ),
  'contact' => 
  array (
    'label' => 'Contact Email',
    'hover_text' => 'Please add a contact email address for your organisation. Please note that IATI is an open data standard and the email provided here will be visible to others on the IATI Registry.',
  ),
  'website' => 
  array (
    'label' => 'Website',
    'hover_text' => 'Add the URL to your organisation\'s website.',
  ),
  'address' => 
  array (
    'label' => 'Address',
    'placeholder' => 'Type address here',
    'hover_text' => 'Provide a contact address for your organisation.',
  ),
  'publishing_additional_info' => 
  array (
    'title' => 'Publishing Additional Information',
    'description' => 'This information will be used to create an admin account in IATI Publisher',
  ),
  'source' => 
  array (
    'label' => 'Source',
    'placeholder' => 'Select a Source',
    'hover_text' => 'Select an option:<br>Primary - your organisation is publishing its own or (associated organisations\') data <br>Secondary - your organisation is reproducing data on the activities of another organisation',
  ),
  'record_exclusions' => 
  array (
    'label' => 'Record Exclusions',
    'placeholder' => 'Type Record Exclusions here',
    'hover_text' => 'Does your organisation have an exclusion policy that provide details on what data that it cannot publish? For example an organisation may not be able to publish data because of political sensitivity issues or if information is commercially restricted. Please provide details here about what data your organisation needs to exclude (if any), and a URL to your organisation\'s exclusion policy (if it has one).<a href=\'https://iatistandard.org/en/guidance/standard-overview/preparing-your-organisation-data-publication/information-and-data-you-cant-publish-exclusions/\' target=\'_blank\'> For more information read: Information and data you can\'t publish (exclusions)</a>',
  ),
  'administrator_information' => 
  array (
    'label' => 'Administrator Information',
    'iati_register_description' => 'Provide your information to create an admin account here on IATI Publisher and IATI Registry at once.',
    'register_description' => 'This information will be used to create an admin account in IATI Publisher',
    'hover_text' => 'Provide your information to create an admin account here on IATI Publisher.',
  ),
  'username' => 
  array (
    'label' => 'Username',
    'placeholder' => 'Type username here',
    'hover_text' => 'You will need this later to login into IATI Publisher.',
  ),
  'fullname' => 
  array (
    'label' => 'Full Name',
    'placeholder' => 'Type your full name here',
  ),
  'email_address' => 
  array (
    'label' => 'Email Address',
    'placeholder' => 'Type valid email here',
  ),
  'password' => 
  array (
    'label' => 'Password',
    'placeholder' => 'Type password here',
    'help_text' => 'Minimum length: 6 characters',
    'new' => 'New password',
    'confirm' => 'Confirm Password',
    'updated' => 'Password Updated!',
    'confirm_help' => 'should match the password above',
    'correct_current' => 'Please enter correct current password',
    'use_new' => 'Please use your new password to login again.',
  ),
  'email_verification' => 
  array (
    'title' => 'Email Verification',
    'description' => 'Please verify and activate your IATI Publisher account through your provided email',
  ),
  'data_license' => 
  array (
    'label' => 'Data License',
    'placeholder' => 'Select a Data License',
    'hover_text' => ' Select the License under which your data is being published. IATI is an open data standard and requires you to make your data available under an open licence so it can be freely used. One of the most frequently used licenses is Creative Commons Attribution. <a href=\'https://iatistandard.org/en/guidance/standard-overview/preparing-your-organisation-data-publication/how-to-license-your-data/\' target=\'_blank\' > For more information read: How to license your data.</a>',
  ),
  'for_eg' => 'For e.g.',
);
