<?php

return [
    'these_values_will_be_automatically_added'                                    => 'These values will be automatically added to your data files.',
    'recommended_defaults_for_activity_data'                                      => 'Recommended defaults for activity data',
    'if_you_are_reporting_both_programmes_parent_activities'                      => 'If you are reporting both programmes (parent activities) and projects (child activities), choose the hierarchical level that most of your activities are at. e.g. parent activity = 1; child activity = 2. If all your activities are at the same level i.e. you have no child activities, then choose 1.',
    'add_a_humanitarian_flag_to_every_activity_that_your_organisation'            => 'Add a \'Humanitarian Flag\' to every activity that your organisation publishes data on. Selecting "Yes" means that your activities are wholly or partially addressing a humanitarian crisis. You can add or remove the flag from individual activities if required later.',
    'whether_the_activity_is_funded_by_official_development_assistance_oda'       => 'Flow type is a way to categorise financial flows. It distinguishes between official development assistance (ODA), other official flows (OOF), or several types of private flows. This default will be applied to all of your activities. It can be overridden for individual activities or transactions if needed.<br><br><a target=\'_blank\' href=\'https://iatistandard.org/en/iati-standard/203/codelists/flowtype/\'>Click here for more information</a>',
    'whether_the_aid_is_untied_tied_or_partially_tied'                            => 'Whether funding is untied, tied, or partially tied. Tied funding must be spent on goods or services procured from a particular country or group of countries. This default will be applied to all of your activities. It can be overridden for individual activities or transactions if needed.<br><br><a target=\'_blank\' href=\'https://iatistandard.org/en/iati-standard/203/codelists/tiedstatus/\'>Click here for more information</a>',
    'optional_defaults_for_activity_data'                                         => 'Optional defaults for activity data',
    'a_code_indicating_the_reason_why_this_activity_does_not_contain'             => 'If you are not able to provide any budgets for your activities, select the reason here.',
    'if_a_publisher_chooses_to_publish_linked_data'                               => 'If a publisher chooses to publish linked data about their IATI activities then allowing them to declare where this data is published would support discovery of it, and any additional information they may choose to publish as Linked Data alongside it.',
    'the_type_of_collaboration_involved_in_the_activitys_disbursements'           => 'The type of collaboration involved in the activity’s disbursements, e.g. “bilateral” or “multilateral”. <a target=\'_blank\' href=\'https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/collaboration-type/\'>For more information</a>',
];

