<?php

return [
    'add_a_title_and_identifier_for_the_activity'                                       => 'es_ Add a title and identifier for the activity',
    'a_short_human_readable_title'                                                      => 'es_ A short, human-readable title. <a href=\'https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/\' target=\'_blank\'>For more information</a>',
    'the_free_text_name_or_description_of_the_item_being_described'                     => 'es_ The free text name or description of the item being described. This can be repeated in multiple languages. <a href=\'https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/narrative/\' target=\'_blank\'>For more information</a>',
    'narrative'                                                                         => 'es_ narrative',
    'type_narrative_here'                                                               => 'es_ Type narrative here',
    'a_code_specifying_the_language_of_text_in_this_element'                            => 'es_ A code specifying the language of text in this element. It is recommended that wherever possible only codes from ISO 639-1 are used. If not present, the default language is assumed. <a href=\'https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/narrative/\' target=\'_blank\'>For more information</a>',
    'if_no_language_is_selected_your_default_language_is_assumed.'                      => 'es_ If no language is selected, your default language is assumed.',
    'a_globally_unique_identifier_for_the_activity'                                     => 'es_ A globally unique identifier for the activity.<br><br>This MUST be prefixed with EITHER the current IATI organisation identifier for the reporting organisation (reporting-org/@ref) OR a previous identifier reported in other-identifier, and suffixed with the organisation’s own activity identifier. The prefix and the suffix should be separated by a hyphen “-“.<br><br>Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates. <a href=\'https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/iati-identifier/\' target=\'_blank\'>For more information</a>',
    'type_activity_identifier_here'                                                     => 'es_ Type activity-identifier here',
    'enter_your_own_unique_activity_identifier_such_as_abbreviation_or_simply_a_number' => 'es_ Enter your own unique activity identifier such as abbreviation or simply a number. Make sure it is unique across all the activities. IATI Publisher will concatenate Organization Identifier and Activity Identifier to autogenerate \'iati-identifier\'.',
    'this_is_autogenerated'                                                             => 'es_ This is autogenerated',
];
