<?php

return [
    'add_a_title_and_identifier_for_the_activity'                                       => 'fr_Add a title and identifier for the activity',
    'a_code_specifying_the_language_of_text_in_this_element'                            => 'fr_Titles in additional languages can be added after you have created your activity.',
    'a_globally_unique_identifier_for_the_activity'                                     => 'fr_A unique identifier for the activity. Once an IATI activity has been published, its identifier cannot change in subsequent updates.',
    'type_activity_identifier_here'                                                     => 'fr_Type identifier here',
    'enter_your_own_unique_activity_identifier_such_as_abbreviation_or_simply_a_number' => 'fr_Enter a string, such as an abbreviation or number, to uniquely identify this activity. IATI Publisher will combine this with your Organisation Identifier to create this activity\'s \'iati-identifier\'.',
    'this_is_autogenerated'                                                             => 'fr_This is auto generated',
];
