#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# php artisan test && \
npx stylelint "resources/**/*.scss" --fix && \
npm run lint && \
npm run lint:fix && \
npx lint-staged && \
composer lint && \
git add .
