#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#php artisan optimize:clear && \
#php artisan command:UpdateJsonFiles && \
#php artisan command:FetchOrganisationRegistrationAgency && \
#php artisan command:SetAppDataJsonCache && \
#php artisan test && \
npx stylelint "resources/**/*.scss" --fix && \
npm run lint && \
npx lint-staged && \
composer lint && \
git add .
